version: '3.5'
services:

  mail-gateway:
    build: .
    image: hshq/mail-gateway:v2
    container_name: mail-gateway
    restart: unless-stopped
    networks:
      - mail
    ports:
      - 25:25
      - 587:587
    volumes:
      - ./tls:/etc/postfix/tls:ro
      - ./additional:/etc/postfix/additional
      #- ./tls/ca.crt:/usr/local/share/ca-certificates/ca.crt:ro
    environment:
      - TZ=${TZ}
      - MAIL_FQDN=${MAIL_FQDN}
      - POSTMASTER_ADDRESS=${POSTMASTER_ADDRESS}
      - POSTFIX_SSL_CERT_FILENAME=cert.pem
      - POSTFIX_SSL_KEY_FILENAME=key.pem
      - CERT_AUTH_METHOD=fingerprint
      #- DISABLE_AMAVIS=true
      #- DISABLE_VIRUS_CHECKS=true
      #- DISABLE_SPAM_CHECKS=true

networks:
  mail:
    driver: bridge
